### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythiaTutorials/physical-oceanography-cookbook#14]
Hi all! What is you plan with the LICENSE? We use Apache 2.0 in Pythia, while Pangeo Gallery notebooks generally use MIT license. The latter is fully permissive AFAIK, so there shouldn't be any issue with converting that to Apache when migrated, but we might also want to keep that as is. Any thoughts?

**Comment by brian-rose** [comment]
Based on discussion with the group, the consensus was to stick with the original license for any repurposed material. So I will switch this repo to MIT license.
